### ISSUE TITLE
Connecting to a store after DI bootstrap

### ISSUE THREAD

**Issue by SethDavenport** [clbond/ng2-redux-form#3]
This is a question from @lemind on gitter, but I think it's a good one.

The README example shows a situation where a raw redux store is created and then `provided` to Angular2. Connecting to ng2-redux-form also happens at bootstrap time.

However the ng2-redux documentation shows examples of the store being configured after bootstrap; typically in the `NgModule` or main App Component class.

The reason we do this is so you can construct your store using middlewares that use dependency injection; if you configure your store at bootstrap time, the DI isn't running yet and this limits what you can do in your middlewares.

So - is it possible to use ng2-redux-form with a store that's constructed after bootstrap (i.e. not with a provider)?

**Comment by clbond** [comment]
Hi Seth. Thank you for the note. Good point about ng2-redux.

[This commit](https://github.com/clbond/ng2-redux-form/commit/acdd8f284b123cb7f1ae467566238ad837f34825) upgrades the project to RC6 and replaces all the examples and README info with normal NgRedux instantiation (instead of using preexisting stores).

I hope this addresses your concerns.

**Comment by SethDavenport** [comment]
Yeah took a look at the new docs - this looks great!
